- name: Configure NTP settings on ESXi host
  vmware_host_ntp:
    hostname: "{{ esxi_hostname }}"
    username: "{{ esxi_username }}"
    password: "{{ esxi_password }}"
    esxi_hostname: "{{ inventory_hostname }}"
    ntp_servers:
      - 0.fr.pool.ntp.org
      - 1.fr.pool.ntp.org
      - 2.fr.pool.ntp.org
    state: present
    validate_certs: no  # Utilisez cette option pour désactiver la vérification des certificats SSL
  delegate_to: localhost

- name: Start NTP service on ESXi host
  vmware_host_service_manager:
    hostname: "{{ esxi_hostname }}"
    username: "{{ esxi_username }}"
    password: "{{ esxi_password }}"
    esxi_hostname: "{{ inventory_hostname }}"
    state: start
    service_name: ntpd
    validate_certs: no  # Utilisez cette option pour désactiver la vérification des certificats SSL
  delegate_to: localhost
